2017-06-04 10:24:46  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    Log.Init()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 10:25:49  ERROR: Thread-1  login response failed, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 127, in handle
    if message == "":
NameError: global name 'message' is not defined

2017-06-04 10:25:51  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 150, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 10:26:24  ERROR: Thread-1  login response failed, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 135, in handle
    raise Exception("client is off")
Exception: client is off

2017-06-04 10:26:26  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 150, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 10:27:23  INFO: Thread-1  new user: zero login success
2017-06-04 10:27:25  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 150, in LoginServer
    # interrupt the program with Ctrl-C
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 10:28:25  INFO: Thread-1  new user: zero login success
2017-06-04 10:28:27  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 151, in LoginServer
    # interrupt the program with Ctrl-C
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 10:43:02  INFO: Thread-1  new user: zero login success
2017-06-04 10:43:04  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 152, in LoginServer
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 10:43:22  INFO: Thread-1  login decode failed
2017-06-04 10:43:22  WARNING: Thread-1  login security check failed, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 67, in CheckPassword
    user_name = decode_message[u'name']
UnboundLocalError: local variable 'decode_message' referenced before assignment

2017-06-04 10:43:28  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 149, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 10:44:51  INFO: Thread-1  login decode failed
2017-06-04 10:44:51  WARNING: Thread-1  login security check failed, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 67, in CheckPassword
    user_name = decode_message[u'name']
UnboundLocalError: local variable 'decode_message' referenced before assignment

2017-06-04 10:44:54  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 149, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 10:45:05  INFO: Thread-1  new user: zero login success
2017-06-04 10:51:38  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 149, in LoginServer
    try:
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 10:53:24  INFO: Thread-2  new user: zero login success
2017-06-04 10:53:27  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 154, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 10:53:32  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 150, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-04 10:54:07  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 150, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-04 10:55:04  ERROR: Thread-1  login response failed, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 121, in handle
    buf = self.request.read(5)
AttributeError: '_socketobject' object has no attribute 'read'

2017-06-04 10:55:34  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 154, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 10:56:15  INFO: Thread-1  new user: zero login success
2017-06-04 10:56:17  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 154, in LoginServer
    # interrupt the program with Ctrl-C
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 10:57:22  INFO: Thread-1  new user: zero login success
2017-06-04 10:57:24  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 155, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 10:59:07  INFO: Thread-1  new user: zero login success
2017-06-04 10:59:09  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 155, in LoginServer
    # interrupt the program with Ctrl-C
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 10:59:45  INFO: Thread-1  new user: zero login success
2017-06-04 10:59:53  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 156, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 11:00:50  INFO: Thread-1  new user: zero login success
2017-06-04 11:04:05  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 156, in LoginServer
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 11:04:11  INFO: Thread-1  new user: zero login success
2017-06-04 11:06:06  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 159, in LoginServer
    # interrupt the program with Ctrl-C
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 11:07:19  INFO: Thread-1  new user: zero login success
2017-06-04 11:07:21  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 160, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 11:07:27  INFO: Thread-1  new user: zero login success
2017-06-04 11:08:19  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 160, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 11:12:30  ERROR: Thread-1  login response failed, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 134, in handle
    def LoginServer(self):
TypeError: cannot concatenate 'str' and 'list' objects

2017-06-04 11:12:32  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 160, in LoginServer
    loginTime = token.rsplit(' ')[-1]
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 11:12:40  INFO: Thread-1  new user: zero login success
2017-06-04 11:13:04  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 144, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 11:13:10  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 140, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-04 11:13:15  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 140, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-04 11:14:42  INFO: Thread-1  new user: zero login success
2017-06-04 11:28:59  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 142, in LoginServer
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-04 11:35:33  INFO: Thread-1  new user: zero login success
2017-06-04 11:36:31  ERROR: Thread-2  login response failed, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 118, in handle
    message = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 451, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer

2017-06-04 11:38:25  INFO: Thread-3  new user: zero login success
