2017-06-02 13:05:54  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 146, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 15:51:21  INFO: Thread-1  new user: zero login success
2017-06-02 16:26:17  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 150, in LoginServer
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 16:26:42  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 163, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 16:27:28  INFO: Thread-1  new user: zero login success
2017-06-02 16:27:28  ERROR: Thread-1  Error: unable to start thread
2017-06-02 16:29:57  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 164, in LoginServer
    # interrupt the program with Ctrl-C
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 16:30:05  INFO: Thread-1  new user: zero login success
2017-06-02 16:30:05  ERROR: Thread-1  Error: unable to start thread
2017-06-02 16:31:08  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 165, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 16:33:38  INFO: Thread-1  new user: zero login success
2017-06-02 16:33:38  ERROR: Thread-1  userinfo info failure
2017-06-02 16:35:14  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 164, in LoginServer
    # interrupt the program with Ctrl-C
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 16:35:26  INFO: Thread-1  new user: zero login success
2017-06-02 16:35:26  ERROR: Thread-1  userinfo info failure
2017-06-02 16:36:22  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 165, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 16:36:29  INFO: Thread-1  new user: zero login success
2017-06-02 16:36:29  ERROR: Thread-1  userinfo info failure
2017-06-02 16:38:02  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 165, in LoginServer
    except :
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 16:40:55  INFO: Thread-1  new user: zero login success
2017-06-02 16:40:55  ERROR: Thread-1  userinfo info failure
2017-06-02 16:43:06  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 164, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 16:43:25  INFO: Thread-1  new user: zero login success
2017-06-02 16:43:25  ERROR: Thread-1  userinfo info failure
2017-06-02 16:44:04  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 164, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 16:44:12  INFO: Thread-1  new user: zero login success
2017-06-02 16:44:12  ERROR: Thread-1  userinfo info failure
2017-06-02 16:45:02  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 164, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 16:45:08  INFO: Thread-1  new user: zero login success
2017-06-02 16:45:46  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 164, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 16:45:51  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 160, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 16:46:22  INFO: Thread-1  new user: zero login success
2017-06-02 16:56:25  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 164, in LoginServer
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 16:56:33  INFO: Thread-1  new user: zero login success
2017-06-02 16:57:09  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 16:57:21  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 137, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 16:59:03  INFO: Thread-1  new user: zero login success
2017-06-02 17:12:26  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 17:12:34  INFO: Thread-1  new user: zero login success
2017-06-02 17:22:11  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 17:22:20  INFO: Thread-1  new user: zero login success
2017-06-02 17:22:45  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 17:22:49  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 137, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 17:23:26  INFO: Thread-1  new user: zero login success
2017-06-02 18:32:27  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 18:32:34  INFO: Thread-1  new user: zero login success
2017-06-02 18:38:16  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 18:38:23  INFO: Thread-1  new user: zero login success
2017-06-02 18:38:58  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 18:39:08  INFO: Thread-1  new user: zero login success
2017-06-02 18:39:47  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 18:39:52  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 137, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 18:40:24  INFO: Thread-1  new user: zero login success
2017-06-02 18:43:39  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 18:43:48  INFO: Thread-1  new user: zero login success
2017-06-02 18:44:08  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 18:44:16  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 137, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 18:44:36  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 137, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 18:45:05  INFO: Thread-1  new user: zero login success
2017-06-02 18:45:46  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 18:45:52  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 137, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 18:46:56  INFO: Thread-1  new user: zero login success
2017-06-02 18:48:50  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 18:48:59  INFO: Thread-1  new user: zero login success
2017-06-02 18:51:17  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 18:51:25  INFO: Thread-1  new user: zero login success
2017-06-02 18:57:40  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 18:57:47  INFO: Thread-1  new user: zero login success
2017-06-02 18:58:57  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 18:59:09  INFO: Thread-1  new user: zero login success
2017-06-02 19:00:43  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 19:00:52  INFO: Thread-1  new user: zero login success
2017-06-02 19:02:04  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 19:02:11  INFO: Thread-1  new user: zero login success
2017-06-02 19:02:35  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 19:02:39  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 137, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 19:02:45  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 137, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 19:03:06  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 137, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 19:03:22  INFO: Thread-1  new user: zero login success
2017-06-02 19:07:28  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 19:07:35  INFO: Thread-1  new user: zero login success
2017-06-02 19:07:35  INFO: Thread-3  new user: zero login success
2017-06-02 19:10:17  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 19:10:24  INFO: Thread-1  new user: zero login success
2017-06-02 19:21:18  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 19:24:54  INFO: Thread-1  new user: zero login success
2017-06-02 19:26:27  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 19:26:35  INFO: Thread-1  new user: zero login success
2017-06-02 19:26:49  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 19:28:30  INFO: Thread-1  new user: zero login success
2017-06-02 19:45:57  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 19:46:04  INFO: Thread-1  new user: zero login success
2017-06-02 19:49:12  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 141, in LoginServer
    # interrupt the program with Ctrl-C
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 19:49:19  INFO: Thread-1  new user: zero login success
2017-06-02 19:49:32  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 142, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 19:49:37  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 138, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 19:51:23  INFO: Thread-1  new user: zero login success
2017-06-02 19:55:22  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 142, in LoginServer
    # interrupt the program with Ctrl-C
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 19:55:30  INFO: Thread-1  new user: zero login success
2017-06-02 20:02:23  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:02:38  INFO: Thread-1  new user: zero login success
2017-06-02 20:02:38  ERROR: Thread-1  userinfo info failure
2017-06-02 20:03:21  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:03:27  INFO: Thread-1  new user: zero login success
2017-06-02 20:03:27  ERROR: Thread-1  userinfo info failure
2017-06-02 20:03:35  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:04:15  INFO: Thread-1  new user: zero login success
2017-06-02 20:06:40  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:06:46  INFO: Thread-1  new user: zero login success
2017-06-02 20:08:36  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:08:44  INFO: Thread-1  new user: zero login success
2017-06-02 20:11:05  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:11:11  INFO: Thread-1  new user: zero login success
2017-06-02 20:12:21  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:13:57  INFO: Thread-1  new user: zero login success
2017-06-02 20:14:12  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:14:25  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 139, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 20:14:39  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 139, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 20:15:03  INFO: Thread-1  new user: zero login success
2017-06-02 20:15:14  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:24:27  INFO: Thread-1  new user: zero login success
2017-06-02 20:25:37  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:25:45  INFO: Thread-1  new user: zero login success
2017-06-02 20:26:59  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:27:07  INFO: Thread-1  new user: zero login success
2017-06-02 20:29:51  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:31:20  INFO: Thread-1  new user: zero login success
2017-06-02 20:32:44  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:32:55  INFO: Thread-1  new user: zero login success
2017-06-02 20:33:29  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:33:35  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 139, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 20:33:40  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 139, in LoginServer
    loginServer = SocketServer.ThreadingTCPServer((LOGIN_HOST, LOGIN_PORT), self.LoginHandeler(self.CheckPassword, Log.error))
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-06-02 20:35:42  INFO: Thread-1  new user: zero login success
2017-06-02 20:37:10  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:37:18  INFO: Thread-1  new user: zero login success
2017-06-02 20:39:38  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:39:46  INFO: Thread-1  new user: zero login success
2017-06-02 20:44:09  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:44:15  INFO: Thread-1  new user: zero login success
2017-06-02 20:52:36  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:53:00  INFO: Thread-1  new user: zero login success
2017-06-02 20:57:12  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

2017-06-02 20:57:19  INFO: Thread-1  new user: zero login success
2017-06-02 20:57:34  ERROR: MainThread  port ERROR, traceback: Traceback (most recent call last):
  File "/home/zero/PycharmProjects/unity (复件)/game/game/server.py", line 143, in LoginServer
    loginServer.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

